import {
  Bell,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ClipboardList,
  FileCheck2,
  FileText,
  Gauge,
  LifeBuoy,
  PackageOpen,
  Settings,
  Truck,
  UserRound,
  UsersRound,
} from "lucide-react"

export const portalIcons: Record<string, typeof Gauge> = {
  dashboard: Gauge,
  profile: UserRound,
  verification: FileCheck2,
  documents: FileCheck2,
  projects: BriefcaseBusiness,
  offers: FileText,
  proposals: FileText,
  tenders: ClipboardList,
  opportunities: BriefcaseBusiness,
  applications: UsersRound,
  workforce: UsersRound,
  "company-requests": Building2,
  "worker-requests": UsersRound,
  equipment: Truck,
  catalogue: PackageOpen,
  catalog: PackageOpen,
  requests: ClipboardList,
  saved: Bookmark,
  messages: Bell,
  enquiries: Bell,
  availability: CalendarDays,
  engagements: ClipboardList,
  workspace: Building2,
  members: UsersRound,
  notifications: Bell,
  settings: Settings,
  support: LifeBuoy,
}
