import {
  Bell,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ClipboardList,
  FileCheck2,
  FileText,
  Gauge,
  PackageOpen,
  Settings,
  Truck,
  UserRound,
  UsersRound,
  Wrench,
} from "lucide-react"

export const portalIcons: Record<string, typeof Gauge> = {
  dashboard: Gauge,
  profile: UserRound,
  documents: FileCheck2,
  projects: BriefcaseBusiness,
  proposals: FileText,
  tenders: ClipboardList,
  "company-requests": Building2,
  "worker-requests": UsersRound,
  equipment: Truck,
  catalog: PackageOpen,
  requests: ClipboardList,
  saved: Bookmark,
  enquiries: Bell,
  availability: CalendarDays,
  subscription: Wrench,
  notifications: Bell,
  settings: Settings,
}
